name: Backend Continuous Integration
on:
  workflow_dispatch:
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a python environment using the specified version.
      - uses: actions/setup-python@v5
        with:
          node-version: '3.10'

      # Install the dependencies.
      - run: cd backend && python -m pip install --upgrade pip
      - run: cd backend && pip install pipenv
      - run: cd backend && pip install flake8

      # Run the linter.
      - run: cd backend && pipenv run lint
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a python environment using the specified version.
      - uses: actions/setup-python@v5
        with:
          node-version: '3.10'

      # Install the dependencies.
      - run: cd backend && python -m pip install --upgrade pip
      - run: cd backend && pip install pipenv
      - run: cd backend && pip install flake8

      # Run the test.
      - run: cd backend && pipenv install pytest && pipenv run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Build docker image
      - run: cd backend && docker build --tag mp-backend:latest .
